# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide6 import QtCore, QtGui, QtWidgets
from AnalogGaugeWidget import AnalogGaugeWidget
import rc_icons

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 434)
        MainWindow.setMaximumSize(QtCore.QSize(4000000, 8000000))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgba(0,35,33,255);")
        self.MainWidget = QtWidgets.QWidget(MainWindow)
        self.MainWidget.setObjectName("MainWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.MainWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.MainWidget)
        self.frame.setMaximumSize(QtCore.QSize(700, 432))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.GaugeRPM = AnalogGaugeWidget(self.frame)
        self.GaugeRPM.setGeometry(QtCore.QRect(160, 10, 371, 432))
        self.GaugeRPM.setStyleSheet("background-color: solid white;")
        self.GaugeRPM.setObjectName("GaugeRPM")
        self.line_2 = QtWidgets.QFrame(self.GaugeRPM)
        self.line_2.setGeometry(QtCore.QRect(-160, 390, 691, 20))
        self.line_2.setStyleSheet("background-color: solid white;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(self.GaugeRPM)
        self.line.setGeometry(QtCore.QRect(-160, -10, 521, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.QLCDOilPressure = QtWidgets.QLCDNumber(self.frame)
        self.QLCDOilPressure.setGeometry(QtCore.QRect(0, 350, 221, 61))
        self.QLCDOilPressure.setStyleSheet("QLCDNumber{\n"
"border:2px solid rgba(255,255,255,255);\n"
"background-color: rgba(0,167,158,255);\n"
"color:rgb(145, 217, 187); \n"
"padding: 30px;\n"
"text-align: right;\n"
"color:white;\n"
"border-top-right-radius: 50px;\n"
"border-bottom-right-radius:0px;\n"
"border-style: outset;\n"
"}")
        self.QLCDOilPressure.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.QLCDOilPressure.setSmallDecimalPoint(True)
        self.QLCDOilPressure.setDigitCount(3)
        self.QLCDOilPressure.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.QLCDOilPressure.setProperty("value", 4.4)
        self.QLCDOilPressure.setProperty("intValue", 4)
        self.QLCDOilPressure.setObjectName("QLCDOilPressure")
        self.QLCDBatteryVoltage = QtWidgets.QLCDNumber(self.frame)
        self.QLCDBatteryVoltage.setGeometry(QtCore.QRect(470, 350, 221, 61))
        self.QLCDBatteryVoltage.setStyleSheet("QLCDNumber{\n"
"border:2px solid rgba(255,255,255,255);\n"
"background-color: rgba(0,167,158,255);\n"
"color:rgb(145, 217, 187); \n"
"padding: 0px;\n"
"text-align: right;\n"
"color:white;\n"
"border-top-left-radius: 50px;\n"
"border-bottom-left-radius:0px;\n"
"border-style: inset;\n"
"}")
        self.QLCDBatteryVoltage.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.QLCDBatteryVoltage.setDigitCount(2)
        self.QLCDBatteryVoltage.setProperty("value", 14.0)
        self.QLCDBatteryVoltage.setProperty("intValue", 14)
        self.QLCDBatteryVoltage.setObjectName("QLCDBatteryVoltage")
        self.QLCDWaterTemp = QtWidgets.QLCDNumber(self.frame)
        self.QLCDWaterTemp.setGeometry(QtCore.QRect(-30, 10, 281, 61))
        self.QLCDWaterTemp.setStyleSheet("QLCDNumber{\n"
"border:2px solid rgba(255,255,255,255);\n"
"background-color: rgba(0,167,158,255);\n"
"color:white; \n"
"padding: 30px;\n"
"color:(255,255,255);\n"
"text-align: left;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-right-radius:50px;\n"
"border-style: inset;\n"
"}")
        self.QLCDWaterTemp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QLCDWaterTemp.setDigitCount(3)
        self.QLCDWaterTemp.setProperty("intValue", 70)
        self.QLCDWaterTemp.setObjectName("QLCDWaterTemp")
        self.QLCDOILTemp = QtWidgets.QLCDNumber(self.frame)
        self.QLCDOILTemp.setGeometry(QtCore.QRect(430, 10, 261, 61))
        self.QLCDOILTemp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.QLCDOILTemp.setStyleSheet("QLCDNumber{\n"
"border:2px solid rgba(255,255,255,255);\n"
"background-color: rgba(0,167,158,255);\n"
"color:rgb(145, 217, 187); \n"
"padding: 30px;\n"
"text-align: center;\n"
"color:white;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-left-radius:50px;\n"
"border-style: inset;\n"
"}")
        self.QLCDOILTemp.setFrameShape(QtWidgets.QFrame.Box)
        self.QLCDOILTemp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.QLCDOILTemp.setLineWidth(5)
        self.QLCDOILTemp.setSmallDecimalPoint(False)
        self.QLCDOILTemp.setDigitCount(3)
        self.QLCDOILTemp.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.QLCDOILTemp.setProperty("value", 10.0)
        self.QLCDOILTemp.setProperty("intValue", 10)
        self.QLCDOILTemp.setObjectName("QLCDOILTemp")
        self.IconWatterTEmp = QtWidgets.QLabel(self.frame)
        self.IconWatterTEmp.setGeometry(QtCore.QRect(0, 13, 61, 56))
        self.IconWatterTEmp.setStyleSheet("image:url(:/icons/icons/coolant-temperature-svgrepo-com_BlackRed.svg);\n"
"background-color:rgba(0,167,158,255);")
        self.IconWatterTEmp.setText("")
        self.IconWatterTEmp.setObjectName("IconWatterTEmp")
        self.IconOILTemp = QtWidgets.QLabel(self.frame)
        self.IconOILTemp.setGeometry(QtCore.QRect(640, 13, 51, 56))
        self.IconOILTemp.setStyleSheet("image:url(:/icons/icons/coolant-temperature-svgrepo-com_BlackRed.svg);\n"
"background-color: red;")
        self.IconOILTemp.setText("")
        self.IconOILTemp.setObjectName("IconOILTemp")
        self.IconOILPressure = QtWidgets.QLabel(self.frame)
        self.IconOILPressure.setGeometry(QtCore.QRect(0, 353, 61, 56))
        self.IconOILPressure.setStyleSheet("image:url(:/icons/icons/oil-pressure-alarm-svgrepo-com_red_Black.svg);\n"
"background-color:solid red;")
        self.IconOILPressure.setText("")
        self.IconOILPressure.setObjectName("IconOILPressure")
        self.Gear = QtWidgets.QLCDNumber(self.frame)
        self.Gear.setGeometry(QtCore.QRect(540, 80, 141, 171))
        self.Gear.setStyleSheet("QLCDNumber{\n"
"border:5px solid red;\n"
"background-color: rgba(0,167,158,255);\n"
"border-radius: 20px; \n"
"color:rgb(145, 217, 187); \n"
"padding: 30px;\n"
"color:white;\n"
"text-align: center;\n"
"border-style: inset;\n"
"}")
        self.Gear.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Gear.setDigitCount(3)
        self.Gear.setProperty("intValue", 100)
        self.Gear.setObjectName("Gear")
        self.IconBattery = QtWidgets.QLabel(self.frame)
        self.IconBattery.setGeometry(QtCore.QRect(639, 352, 51, 57))
        self.IconBattery.setStyleSheet("image:url(:/icons/icons/charging-circuit-failure-svgrepo-com.svg);\n"
"background-color: red;")
        self.IconBattery.setText("")
        self.IconBattery.setObjectName("IconBattery")
        self.NeedToDiscuss = QtWidgets.QLCDNumber(self.frame)
        self.NeedToDiscuss.setGeometry(QtCore.QRect(10, 80, 141, 261))
        self.NeedToDiscuss.setStyleSheet("QLCDNumber{\n"
"border:10px solid red;\n"
"background-color: rgba(0,167,158,255);\n"
"border-radius: 20px; \n"
"color:rgb(145, 217, 187); \n"
"padding: 30px;\n"
"color:white;\n"
"text-align: center;\n"
"border-style: inset; \n"
"}")
        self.NeedToDiscuss.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.NeedToDiscuss.setDigitCount(1)
        self.NeedToDiscuss.setProperty("value", 2.0)
        self.NeedToDiscuss.setProperty("intValue", 2)
        self.NeedToDiscuss.setObjectName("NeedToDiscuss")
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(680, 10, 20, 401))
        self.line_4.setStyleSheet("background-color:solid white;")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(570, 200, 121, 41))
        self.label.setStyleSheet("font: 700 italic 32pt \"Times New Roman\";\n"
"color:black;\n"
"background-color: rgba(0,0,0,0);")
        self.label.setObjectName("label")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber.setGeometry(QtCore.QRect(543, 252, 141, 91))
        self.lcdNumber.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lcdNumber.setStyleSheet("QLCDNumber{\n"
"border:5px solid red;\n"
"background-color: rgba(0,167,158,255);\n"
"border-radius: 20px; \n"
"color:rgb(145, 217, 187); \n"
"padding: 30px;\n"
"color:white;\n"
"text-align: center;\n"
"border-style: inset;\n"
"}")
        self.lcdNumber.setDigitCount(6)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(560, 320, 131, 16))
        self.label_2.setStyleSheet("font: 700 italic 12pt \"Times New Roman\";\n"
"color:black;\n"
"background-color: rgba(0,0,0,0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(150, 45, 49, 21))
        self.label_3.setStyleSheet("font: 700 italic 22pt \"Times New Roman\";\n"
"color:black;\n"
"background-color: rgba(0,0,0,0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(600, 40, 49, 31))
        self.label_4.setStyleSheet("font: 700 italic 22pt \"Times New Roman\";\n"
"color:black;\n"
"background-color: rgba(0,0,0,0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(160, 385, 49, 21))
        self.label_5.setStyleSheet("font: 700 italic 22pt \"Times New Roman\";\n"
"color:black;\n"
"background-color: rgba(0,0,0,0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(600, 360, 49, 61))
        self.label_6.setStyleSheet("font: 700 italic 22pt \"Times New Roman\";\n"
"color:black;\n"
"background-color: rgba(0,0,0,0);")
        self.label_6.setObjectName("label_6")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(-10, 10, 20, 401))
        self.line_3.setStyleSheet("background-color: solid white;")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.GaugeRPM.raise_()
        self.QLCDOilPressure.raise_()
        self.QLCDBatteryVoltage.raise_()
        self.QLCDWaterTemp.raise_()
        self.QLCDOILTemp.raise_()
        self.NeedToDiscuss.raise_()
        self.IconWatterTEmp.raise_()
        self.IconOILPressure.raise_()
        self.IconOILTemp.raise_()
        self.IconBattery.raise_()
        self.Gear.raise_()
        self.label.raise_()
        self.lcdNumber.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.verticalLayout_3.addWidget(self.frame)
        MainWindow.setCentralWidget(self.MainWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Km/h"))
        self.label_2.setText(_translate("MainWindow", "HH:MM:SS"))
        self.label_3.setText(_translate("MainWindow", "°C "))
        self.label_4.setText(_translate("MainWindow", "°C "))
        self.label_5.setText(_translate("MainWindow", "bar"))
        self.label_6.setText(_translate("MainWindow", "  V"))
